services:
  postgres:
    image: postgres:17-alpine3.21
    container_name: fluxreader-postgres
    restart: unless-stopped
    env_file:
      - ./rss.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - fluxreader-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fluxreader-backend
    restart: unless-stopped
    env_file:
      - ./rss.env
    ports:
      - "8000:8000"
    networks:
      - fluxreader-network
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/.venv
      - /app/__pycache__

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fluxreader-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - fluxreader-network
    depends_on:
      - backend
    env_file:
      - ./rss.env

# Networks
networks:
  fluxreader-network:
    driver: bridge
    name: fluxreader-network

# Volumes
volumes:
  postgres_data:
    driver: local
    name: fluxreader-postgres-data
