# Grafana Datasource Configuration
# Automatically configures Prometheus as a datasource
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
