# Simple RSS Reader Monitoring Stack
# Easy setup for beginners - just run: docker compose up -d
#
# Access:
#   - Grafana: http://localhost:3001 (admin/admin)
#   - Prometheus: http://localhost:9090

services:
  # Prometheus - Collects metrics from your RSS Reader
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - monitoring

  # Grafana - Creates dashboards and charts
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config:/etc/grafana/provisioning:ro
    networks:
      - monitoring
    depends_on:
      - prometheus

# Networks and Volumes
networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
